name: rngtr

channels:
  - pytorch
  - defaults
  - conda-forge

dependencies:
  - certifi
  - cffi
  - cudatoolkit
  - cudnn
  - freetype
  - intel-openmp=2019.4
  - joblib
  - jpeg
  - ld_impl_linux-64=2.33
  - libedit=3.1
  - libffi=3.2
  - libgcc-ng=9.1
  - libgfortran-ng=7.3.0
  - libpng=1.6.37
  - libstdcxx-ng=9.1.0
  - libtiff=4.1.0
  - mkl
  - mkl-service
  - mkl_fft
  - mkl_random
  - ninja
  - pillow
  - pip
  - pycparser
  - python=3.7.6
  - pytorch
  - readline
  - regex
  - scikit-learn=0.22.1
  - setuptools
  - six
  - sqlite=3.30.1
  - tk=8.6.8
  - torchvision
  - tqdm
  - wheel
  - zlib
  - zstd
